# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20160826_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='username',
        ),
    ]
