# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20160828_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='username',
            new_name='user',
        ),
    ]
